apiVersion: v1
kind: PersistentVolume
metadata:
  name: <name of pv>
spec:
  capacity:
    storage: <storage capacity>
  accessModes:
    - <access mode>
  nfs:
    path: <NFS share path>
    server: <NFS server FQDN>

